import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../../core/themes/spacings.dart';
import '../../../../core/themes/app_typography.dart';
import '../../../../core/extensions/context_extensions.dart';
import '../../../../shared/widgets/app_button.dart';
import '../../../../shared/widgets/app_card.dart';
import '../../../../shared/widgets/app_text_field.dart';
import '../../../../shared/widgets/app_loading.dart';
import '../../../../shared/widgets/app_app_bar.dart';
import '../../../../shared/widgets/app_empty_state.dart';
import '../../../../shared/widgets/app_error_state.dart';
import '../../../../routing/route_names.dart';
import '../../domain/entities/teacher_workspace_entities.dart';
import '../providers/scheme_of_work_provider.dart';
import '../widgets/generate_questions_button.dart';

// ═══════════════════════════════════════════════════════════════════════
// SCHEME OF WORK LIST PAGE
// ═══════════════════════════════════════════════════════════════════════

/// List page for all schemes of work created or generated by the teacher.
///
/// Features search, filter by curriculum and duration type, pull-to-refresh,
/// and a FAB to create a new scheme.
class SchemeOfWorkListPage extends ConsumerStatefulWidget {
  const SchemeOfWorkListPage({super.key});

  @override
  ConsumerState<SchemeOfWorkListPage> createState() =>
      _SchemeOfWorkListPageState();
}

class _SchemeOfWorkListPageState extends ConsumerState<SchemeOfWorkListPage> {
  final _searchController = TextEditingController();
  bool _isSearchMode = false;
  CurriculumType? _filterCurriculum;
  PlanDuration? _filterDurationType;

  @override
  void initState() {
    super.initState();
    Future.microtask(() {
      ref.read(schemeOfWorkProvider.notifier).loadSchemes();
    });
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  // ─── Filter Helpers ───────────────────────────────────────────────

  List<SchemeOfWorkEntity> _applyFilters(List<SchemeOfWorkEntity> schemes) {
    var result = schemes;

    // Search filter
    if (_isSearchMode && _searchController.text.isNotEmpty) {
      final query = _searchController.text.toLowerCase();
      result = result
          .where((s) =>
              s.title.toLowerCase().contains(query) ||
              s.subject.toLowerCase().contains(query) ||
              (s.className?.toLowerCase().contains(query) ?? false))
          .toList();
    }

    // Curriculum filter
    if (_filterCurriculum != null) {
      result = result.where((s) => s.curriculum == _filterCurriculum).toList();
    }

    // Duration type filter
    if (_filterDurationType != null) {
      result =
          result.where((s) => s.durationType == _filterDurationType).toList();
    }

    return result;
  }

  void _clearFilters() {
    setState(() {
      _filterCurriculum = null;
      _filterDurationType = null;
      _searchController.clear();
      _isSearchMode = false;
    });
  }

  // ─── Refresh ──────────────────────────────────────────────────────

  Future<void> _refresh() async {
    await ref.read(schemeOfWorkProvider.notifier).loadSchemes();
  }

  // ─── Filter Bottom Sheet ──────────────────────────────────────────

  void _showFilterBottomSheet(ColorScheme cs, TextTheme tt) {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(Spacings.lgRadius),
        ),
      ),
      builder: (ctx) => StatefulBuilder(
        builder: (ctx, setSheetState) => Padding(
          padding: const EdgeInsets.all(Spacings.lg),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Filter Schemes',
                    style: tt.titleMedium?.copyWith(
                      fontWeight: AppTypography.wSemiBold,
                      color: cs.onSurface,
                    ),
                  ),
                  if (_filterCurriculum != null || _filterDurationType != null)
                    TextButton(
                      onPressed: () {
                        setSheetState(() {});
                        setState(() {
                          _filterCurriculum = null;
                          _filterDurationType = null;
                        });
                      },
                      child: Text('Clear All',
                          style: tt.bodyMedium?.copyWith(color: cs.error)),
                    ),
                ],
              ),
              const SizedBox(height: Spacings.lg),

              // Curriculum filter
              Text('Curriculum',
                  style: tt.labelMedium?.copyWith(
                    color: cs.primary,
                    fontWeight: AppTypography.wSemiBold,
                  )),
              const SizedBox(height: Spacings.sm),
              Wrap(
                spacing: Spacings.sm,
                runSpacing: Spacings.sm,
                children: CurriculumType.values.map((c) {
                  final selected = _filterCurriculum == c;
                  return ChoiceChip(
                    label: Text(c.label),
                    selected: selected,
                    onSelected: (_) {
                      setSheetState(() {});
                      setState(() {
                        _filterCurriculum = selected ? null : c;
                      });
                    },
                  );
                }).toList(),
              ),
              const SizedBox(height: Spacings.lg),

              // Duration type filter
              Text('Duration Type',
                  style: tt.labelMedium?.copyWith(
                    color: cs.primary,
                    fontWeight: AppTypography.wSemiBold,
                  )),
              const SizedBox(height: Spacings.sm),
              Wrap(
                spacing: Spacings.sm,
                runSpacing: Spacings.sm,
                children: PlanDuration.values.map((d) {
                  final selected = _filterDurationType == d;
                  return ChoiceChip(
                    label: Text(d.label),
                    selected: selected,
                    onSelected: (_) {
                      setSheetState(() {});
                      setState(() {
                        _filterDurationType = selected ? null : d;
                      });
                    },
                  );
                }).toList(),
              ),
              const SizedBox(height: Spacings.xl),

              // Apply button
              SizedBox(
                width: double.infinity,
                child: AppButton(
                  label: 'Apply Filters',
                  onPressed: () => Navigator.pop(ctx),
                  variant: AppButtonVariant.elevated,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // ─── Build ────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    final cs = context.colorScheme;
    final tt = context.textTheme;
    final state = ref.watch(schemeOfWorkProvider);

    ref.listen<SchemeOfWorkState>(schemeOfWorkProvider, (prev, next) {
      if (next.error != null && prev?.error != next.error) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(next.error!), backgroundColor: cs.error),
        );
        ref.read(schemeOfWorkProvider.notifier).clearError();
      }
      if (next.successMessage != null &&
          prev?.successMessage != next.successMessage) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text(next.successMessage!), backgroundColor: cs.primary),
        );
        ref.read(schemeOfWorkProvider.notifier).clearSuccessMessage();
      }
    });

    final filteredSchemes = _applyFilters(state.schemes);

    return Scaffold(
      appBar: AppAppBar(
        title: 'Schemes of Work',
        isSearchMode: _isSearchMode,
        searchController: _searchController,
        onSearchToggle: () {
          setState(() {
            _isSearchMode = !_isSearchMode;
            if (!_isSearchMode) _searchController.clear();
          });
        },
        onSearchChanged: (_) => setState(() {}),
        actions: [
          IconButton(
            icon: Icon(Icons.filter_list_outlined, color: cs.onSurfaceVariant),
            tooltip: 'Filter',
            onPressed: () => _showFilterBottomSheet(cs, tt),
          ),
        ],
      ),
      body: _buildBody(cs, tt, state, filteredSchemes),
      floatingActionButton: AppFloatingActionButton(
        label: 'New Scheme',
        icon: Icons.add,
        extended: true,
        onPressed: () {
          context.push('/workspace/scheme-of-work/generator');
        },
      ),
    );
  }

  // ─── Body ─────────────────────────────────────────────────────────

  Widget _buildBody(ColorScheme cs, TextTheme tt, SchemeOfWorkState state,
      List<SchemeOfWorkEntity> filteredSchemes) {
    if (state.isLoading) {
      return const Center(child: AppLoadingSpinner(size: AppLoadingSpinnerSize.large));
    }

    if (state.error != null && state.schemes.isEmpty) {
      return AppErrorState.genericError(
        message: state.error,
        onRetry: _refresh,
      );
    }

    if (filteredSchemes.isEmpty) {
      return _isSearchMode || _filterCurriculum != null || _filterDurationType != null
          ? AppEmptyState.noResults(
              subtitle: 'No schemes match your search or filters.',
              onAction: _clearFilters,
            )
          : AppEmptyState(
              icon: Icons.map_outlined,
              title: 'No Schemes Yet',
              subtitle: 'Create your first scheme of work with AI assistance.',
              actionLabel: 'Create Scheme',
              onAction: () {
                context.push('/workspace/scheme-of-work/generator');
              },
            );
    }

    return RefreshIndicator(
      onRefresh: _refresh,
      child: ListView.separated(
        padding: const EdgeInsets.only(
          left: Spacings.lg,
          right: Spacings.lg,
          top: Spacings.md,
          bottom: 100, // space for FAB
        ),
        itemCount: filteredSchemes.length,
        separatorBuilder: (_, __) => const SizedBox(height: Spacings.md),
        itemBuilder: (context, index) {
          return _buildSchemeCard(cs, tt, filteredSchemes[index]);
        },
      ),
    );
  }

  // ─── Scheme Card ──────────────────────────────────────────────────

  Widget _buildSchemeCard(
      ColorScheme cs, TextTheme tt, SchemeOfWorkEntity scheme) {
    return AppCard(
      onTap: () {
        // Navigate to detail/view page
        context.push('/workspace/scheme-of-work/generator');
      },
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Title row
          Row(
            children: [
              Expanded(
                child: Text(
                  scheme.title,
                  style: tt.titleSmall?.copyWith(
                    fontWeight: AppTypography.wSemiBold,
                    color: cs.onSurface,
                  ),
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              if (scheme.isAiGenerated)
                Padding(
                  padding: const EdgeInsets.only(left: Spacings.sm),
                  child: Icon(Icons.auto_awesome,
                      size: Spacings.smIcon, color: cs.tertiary),
                ),
            ],
          ),
          const SizedBox(height: Spacings.sm),

          // Subject & class
          Text(
            '${scheme.subject}${scheme.className != null ? ' \u00b7 ${scheme.className}' : ''}',
            style: tt.bodyMedium?.copyWith(color: cs.onSurfaceVariant),
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
          const SizedBox(height: Spacings.sm),

          // Badge row
          Wrap(
            spacing: Spacings.sm,
            runSpacing: Spacings.xs,
            children: [
              // Duration type badge
              _buildBadge(
                cs,
                tt,
                scheme.durationType.label,
                cs.secondaryContainer,
                cs.onSecondaryContainer,
              ),
              // Curriculum badge
              _buildBadge(
                cs,
                tt,
                scheme.curriculum.label,
                cs.tertiaryContainer,
                cs.onTertiaryContainer,
              ),
              // Term badge
              if (scheme.term != null)
                _buildBadge(
                  cs,
                  tt,
                  scheme.term!,
                  cs.primaryContainer,
                  cs.onPrimaryContainer,
                ),
            ],
          ),
          const SizedBox(height: Spacings.sm),

          // Week count
          Text(
            '${scheme.weeklyPlans.length} ${scheme.durationType == PlanDuration.weekly ? 'weeks' : scheme.durationType == PlanDuration.monthly ? 'months' : 'periods'}',
            style: tt.bodySmall?.copyWith(color: cs.onSurfaceVariant),
          ),
          const SizedBox(height: Spacings.md),

          // Bottom actions row
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              GenerateQuestionsButton(
                resourceType: 'scheme_of_work',
                resourceId: scheme.id,
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildBadge(ColorScheme cs, TextTheme tt, String label,
      Color bgColor, Color fgColor) {
    return Container(
      padding: const EdgeInsets.symmetric(
        horizontal: Spacings.sm,
        vertical: Spacings.xs,
      ),
      decoration: BoxDecoration(
        color: bgColor,
        borderRadius: BorderRadius.circular(Spacings.smRadius),
      ),
      child: Text(
        label,
        style: tt.labelSmall?.copyWith(
          color: fgColor,
          fontWeight: AppTypography.wMedium,
        ),
      ),
    );
  }
}
