import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../../core/extensions/context_extensions.dart';
import '../../../../core/themes/app_typography.dart';
import '../../../../core/themes/spacings.dart';
import '../../../../shared/widgets/app_app_bar.dart';
import '../../../../shared/widgets/app_button.dart';
import '../../../../shared/widgets/app_card.dart';
import '../../../../shared/widgets/app_empty_state.dart';
import '../../../../shared/widgets/app_error_state.dart';
import '../../../../shared/widgets/app_loading.dart';
import '../../domain/entities/teacher_workspace_entities.dart';
import '../../domain/usecases/export_worksheet_usecase.dart';
import '../providers/worksheet_provider.dart';
import '../widgets/generate_questions_button.dart';

// ═══════════════════════════════════════════════════════════════════════
// WORKSHEET LIST PAGE
// ═══════════════════════════════════════════════════════════════════════

/// List page for all worksheets created or generated by the teacher.
///
/// Features search, filter by worksheet type and difficulty, pull-to-refresh,
/// and a FAB to create a new worksheet. Each card shows export and
/// generate-questions action buttons.
class WorksheetListPage extends ConsumerStatefulWidget {
  const WorksheetListPage({super.key});

  @override
  ConsumerState<WorksheetListPage> createState() =>
      _WorksheetListPageState();
}

class _WorksheetListPageState extends ConsumerState<WorksheetListPage> {
  final _searchController = TextEditingController();
  bool _isSearchMode = false;
  WorksheetType? _filterType;
  String? _filterDifficulty;

  @override
  void initState() {
    super.initState();
    Future.microtask(() {
      ref.read(worksheetProvider.notifier).loadWorksheets();
    });
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  // ─── Filter Helpers ───────────────────────────────────────────────

  List<WorksheetEntity> _applyFilters(List<WorksheetEntity> worksheets) {
    var result = worksheets;

    // Search filter
    if (_isSearchMode && _searchController.text.isNotEmpty) {
      final query = _searchController.text.toLowerCase();
      result = result
          .where((w) =>
              w.title.toLowerCase().contains(query) ||
              w.subject.toLowerCase().contains(query) ||
              (w.topic?.toLowerCase().contains(query) ?? false),)
          .toList();
    }

    // Type filter
    if (_filterType != null) {
      result = result.where((w) => w.worksheetType == _filterType).toList();
    }

    // Difficulty filter
    if (_filterDifficulty != null) {
      result = result.where((w) => w.difficulty == _filterDifficulty).toList();
    }

    return result;
  }

  void _clearFilters() {
    setState(() {
      _filterType = null;
      _filterDifficulty = null;
      _searchController.clear();
      _isSearchMode = false;
    });
  }

  // ─── Refresh ──────────────────────────────────────────────────────

  Future<void> _refresh() async {
    await ref.read(worksheetProvider.notifier).loadWorksheets();
  }

  // ─── Export ───────────────────────────────────────────────────────

  void _exportWorksheet(String worksheetId, String format) {
    ref.read(worksheetProvider.notifier).exportWorksheet(
          ExportWorksheetParams(
            worksheetId: worksheetId,
            format: format,
          ),
        );
  }

  // ─── Filter Bottom Sheet ──────────────────────────────────────────

  void _showFilterBottomSheet(ColorScheme cs, TextTheme tt) {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(Spacings.lgRadius),
        ),
      ),
      builder: (ctx) => StatefulBuilder(
        builder: (ctx, setSheetState) => Padding(
          padding: const EdgeInsets.all(Spacings.lg),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Filter Worksheets',
                    style: tt.titleMedium?.copyWith(
                      fontWeight: AppTypography.wSemiBold,
                      color: cs.onSurface,
                    ),
                  ),
                  if (_filterType != null || _filterDifficulty != null)
                    TextButton(
                      onPressed: () {
                        setSheetState(() {});
                        setState(() {
                          _filterType = null;
                          _filterDifficulty = null;
                        });
                      },
                      child: Text('Clear All',
                          style: tt.bodyMedium?.copyWith(color: cs.error),),
                    ),
                ],
              ),
              const SizedBox(height: Spacings.lg),

              // Worksheet type filter
              Text('Worksheet Type',
                  style: tt.labelMedium?.copyWith(
                    color: cs.primary,
                    fontWeight: AppTypography.wSemiBold,
                  ),),
              const SizedBox(height: Spacings.sm),
              Wrap(
                spacing: Spacings.sm,
                runSpacing: Spacings.sm,
                children: WorksheetType.values.map((t) {
                  final selected = _filterType == t;
                  return ChoiceChip(
                    label: Text(t.label),
                    selected: selected,
                    onSelected: (_) {
                      setSheetState(() {});
                      setState(() {
                        _filterType = selected ? null : t;
                      });
                    },
                  );
                }).toList(),
              ),
              const SizedBox(height: Spacings.lg),

              // Difficulty filter
              Text('Difficulty',
                  style: tt.labelMedium?.copyWith(
                    color: cs.primary,
                    fontWeight: AppTypography.wSemiBold,
                  ),),
              const SizedBox(height: Spacings.sm),
              Wrap(
                spacing: Spacings.sm,
                runSpacing: Spacings.sm,
                children: ['easy', 'medium', 'hard'].map((d) {
                  final selected = _filterDifficulty == d;
                  return ChoiceChip(
                    label: Text(d[0].toUpperCase() + d.substring(1)),
                    selected: selected,
                    onSelected: (_) {
                      setSheetState(() {});
                      setState(() {
                        _filterDifficulty = selected ? null : d;
                      });
                    },
                  );
                }).toList(),
              ),
              const SizedBox(height: Spacings.xl),

              // Apply button
              SizedBox(
                width: double.infinity,
                child: AppButton(
                  label: 'Apply Filters',
                  onPressed: () => Navigator.pop(ctx),
                  variant: AppButtonVariant.elevated,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // ─── Build ────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    final cs = context.colorScheme;
    final tt = context.textTheme;
    final state = ref.watch(worksheetProvider);

    ref.listen<WorksheetState>(worksheetProvider, (prev, next) {
      if (next.error != null && prev?.error != next.error) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(next.error!), backgroundColor: cs.error),
        );
        ref.read(worksheetProvider.notifier).clearError();
      }
      if (next.successMessage != null &&
          prev?.successMessage != next.successMessage) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text(next.successMessage!), backgroundColor: cs.primary,),
        );
        ref.read(worksheetProvider.notifier).clearSuccessMessage();
      }
    });

    final filteredWorksheets = _applyFilters(state.worksheets);

    return Scaffold(
      appBar: AppAppBar(
        title: 'Worksheets',
        isSearchMode: _isSearchMode,
        searchController: _searchController,
        onSearchToggle: () {
          setState(() {
            _isSearchMode = !_isSearchMode;
            if (!_isSearchMode) _searchController.clear();
          });
        },
        onSearchChanged: (_) => setState(() {}),
        actions: [
          IconButton(
            icon: Icon(Icons.filter_list_outlined, color: cs.onSurfaceVariant),
            tooltip: 'Filter',
            onPressed: () => _showFilterBottomSheet(cs, tt),
          ),
        ],
      ),
      body: _buildBody(cs, tt, state, filteredWorksheets),
      floatingActionButton: AppFloatingActionButton(
        label: 'New Worksheet',
        icon: Icons.add,
        extended: true,
        onPressed: () {
          context.push('/workspace/worksheet/generator');
        },
      ),
    );
  }

  // ─── Body ─────────────────────────────────────────────────────────

  Widget _buildBody(ColorScheme cs, TextTheme tt, WorksheetState state,
      List<WorksheetEntity> filteredWorksheets,) {
    if (state.isLoading) {
      return const Center(
          child: AppLoadingSpinner(size: AppLoadingSpinnerSize.large),);
    }

    if (state.error != null && state.worksheets.isEmpty) {
      return AppErrorState.genericError(
        message: state.error,
        onRetry: _refresh,
      );
    }

    if (filteredWorksheets.isEmpty) {
      return _isSearchMode ||
              _filterType != null ||
              _filterDifficulty != null
          ? AppEmptyState.noResults(
              subtitle: 'No worksheets match your search or filters.',
              onAction: _clearFilters,
            )
          : AppEmptyState(
              icon: Icons.assignment_outlined,
              title: 'No Worksheets Yet',
              subtitle: 'Create your first worksheet with AI assistance.',
              actionLabel: 'Create Worksheet',
              onAction: () {
                context.push('/workspace/worksheet/generator');
              },
            );
    }

    return RefreshIndicator(
      onRefresh: _refresh,
      child: ListView.separated(
        padding: const EdgeInsets.only(
          left: Spacings.lg,
          right: Spacings.lg,
          top: Spacings.md,
          bottom: 100, // space for FAB
        ),
        itemCount: filteredWorksheets.length,
        separatorBuilder: (_, __) => const SizedBox(height: Spacings.md),
        itemBuilder: (context, index) {
          return _buildWorksheetCard(cs, tt, filteredWorksheets[index]);
        },
      ),
    );
  }

  // ─── Worksheet Card ───────────────────────────────────────────────

  Widget _buildWorksheetCard(
      ColorScheme cs, TextTheme tt, WorksheetEntity worksheet,) {
    return AppCard(
      onTap: () {
        context.push('/workspace/worksheet/generator');
      },
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Title row
          Row(
            children: [
              Expanded(
                child: Text(
                  worksheet.title,
                  style: tt.titleSmall?.copyWith(
                    fontWeight: AppTypography.wSemiBold,
                    color: cs.onSurface,
                  ),
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              if (worksheet.isAiGenerated)
                Padding(
                  padding: const EdgeInsets.only(left: Spacings.sm),
                  child: Icon(Icons.auto_awesome,
                      size: Spacings.smIcon, color: cs.tertiary,),
                ),
            ],
          ),
          const SizedBox(height: Spacings.sm),

          // Subject & topic
          Text(
            '${worksheet.subject}${worksheet.topic != null ? ' \u00b7 ${worksheet.topic}' : ''}',
            style: tt.bodyMedium?.copyWith(color: cs.onSurfaceVariant),
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
          const SizedBox(height: Spacings.sm),

          // Badge row
          Wrap(
            spacing: Spacings.sm,
            runSpacing: Spacings.xs,
            children: [
              // Type badge
              _buildBadge(
                cs,
                tt,
                worksheet.worksheetType.label,
                cs.secondaryContainer,
                cs.onSecondaryContainer,
              ),
              // Difficulty badge
              _buildBadge(
                cs,
                tt,
                worksheet.difficulty[0].toUpperCase() +
                    worksheet.difficulty.substring(1),
                _difficultyColor(cs, worksheet.difficulty),
                _difficultyOnColor(cs, worksheet.difficulty),
              ),
            ],
          ),
          const SizedBox(height: Spacings.sm),

          // Stats row: question count & total marks
          Row(
            children: [
              Icon(Icons.quiz_outlined,
                  size: Spacings.smIcon, color: cs.onSurfaceVariant,),
              const SizedBox(width: Spacings.xs),
              Text(
                '${worksheet.questions.length} questions',
                style: tt.bodySmall?.copyWith(color: cs.onSurfaceVariant),
              ),
              const SizedBox(width: Spacings.md),
              Icon(Icons.grade_outlined,
                  size: Spacings.smIcon, color: cs.onSurfaceVariant,),
              const SizedBox(width: Spacings.xs),
              Text(
                '${worksheet.totalMarks.toInt()} marks',
                style: tt.bodySmall?.copyWith(color: cs.onSurfaceVariant),
              ),
              if (worksheet.durationMinutes != null) ...[
                const SizedBox(width: Spacings.md),
                Icon(Icons.timer_outlined,
                    size: Spacings.smIcon, color: cs.onSurfaceVariant,),
                const SizedBox(width: Spacings.xs),
                Text(
                  '${worksheet.durationMinutes} min',
                  style:
                      tt.bodySmall?.copyWith(color: cs.onSurfaceVariant),
                ),
              ],
            ],
          ),
          const SizedBox(height: Spacings.md),

          // Bottom actions row
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              // Export dropdown
              PopupMenuButton<String>(
                onSelected: (format) =>
                    _exportWorksheet(worksheet.id, format),
                position: PopupMenuPosition.under,
                child: const AppButton(
                  label: 'Export',
                  onPressed: null, // handled by popup
                  variant: AppButtonVariant.outlined,
                  size: AppButtonSize.small,
                  icon: Icons.file_download_outlined,
                ),
                itemBuilder: (ctx) => [
                  const PopupMenuItem(
                      value: 'pdf', child: Text('Export as PDF'),),
                  const PopupMenuItem(
                      value: 'docx', child: Text('Export as DOCX'),),
                ],
              ),
              const SizedBox(width: Spacings.sm),

              // Generate Questions
              GenerateQuestionsButton(
                resourceType: 'worksheet',
                resourceId: worksheet.id,
                resourceName: worksheet.title,
              ),
            ],
          ),
        ],
      ),
    );
  }

  // ─── Badge Helpers ────────────────────────────────────────────────

  Widget _buildBadge(ColorScheme cs, TextTheme tt, String label,
      Color bgColor, Color fgColor,) {
    return Container(
      padding: const EdgeInsets.symmetric(
        horizontal: Spacings.sm,
        vertical: Spacings.xs,
      ),
      decoration: BoxDecoration(
        color: bgColor,
        borderRadius: BorderRadius.circular(Spacings.smRadius),
      ),
      child: Text(
        label,
        style: tt.labelSmall?.copyWith(
          color: fgColor,
          fontWeight: AppTypography.wMedium,
        ),
      ),
    );
  }

  Color _difficultyColor(ColorScheme cs, String difficulty) {
    switch (difficulty) {
      case 'easy':
        return const Color(0xFFDCFCE7); // green-100
      case 'hard':
        return const Color(0xFFFEE2E2); // red-100
      default:
        return cs.tertiaryContainer;
    }
  }

  Color _difficultyOnColor(ColorScheme cs, String difficulty) {
    switch (difficulty) {
      case 'easy':
        return const Color(0xFF166534); // green-800
      case 'hard':
        return const Color(0xFF991B1B); // red-800
      default:
        return cs.onTertiaryContainer;
    }
  }
}
