// ============================================================================
// ExamForge AI — Enterprise Alert Engine
// ============================================================================
//
// Evaluates system health, metrics, and crash data to generate alerts:
//   - Crash spikes (rate exceeds threshold)
//   - Authentication failures (consecutive auth errors)
//   - Slow APIs (latency exceeds threshold)
//   - Database timeouts
//   - AI failures
//   - Storage failures
//   - Realtime disconnects
//   - Queue growth (sync queue growing beyond threshold)
//   - Sync failures
//   - Rate limit spikes
//
// Critical alerts support escalation with configurable tiers.
//
// ROOT CAUSE: The project has no alerting infrastructure. Production
// issues are invisible until users report them. This module provides
// proactive alerting for operational visibility.
// ============================================================================

import 'dart:collection';

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../logging/structured_logger.dart';

// ═══════════════════════════════════════════════════════════════════════════
// ALERT SEVERITY
// ═══════════════════════════════════════════════════════════════════════════

/// Severity levels for alerts.
enum AlertSeverity {
  info('info', 0),
  warning('warning', 1),
  critical('critical', 2),
  emergency('emergency', 3);

  const AlertSeverity(this.label, this.priority);
  final String label;
  final int priority;
}

// ═══════════════════════════════════════════════════════════════════════════
// ALERT CATEGORY
// ═══════════════════════════════════════════════════════════════════════════

/// Categories of alerts matching the required monitoring domains.
enum AlertCategory {
  crashSpike('crash_spike'),
  authFailure('auth_failure'),
  slowApi('slow_api'),
  databaseTimeout('database_timeout'),
  aiFailure('ai_failure'),
  storageFailure('storage_failure'),
  realtimeDisconnect('realtime_disconnect'),
  queueGrowth('queue_growth'),
  syncFailure('sync_failure'),
  rateLimitSpike('rate_limit_spike');

  const AlertCategory(this.label);
  final String label;
}

// ═══════════════════════════════════════════════════════════════════════════
// ALERT
// ═══════════════════════════════════════════════════════════════════════════

/// An alert generated by the alert engine.
class Alert {
  Alert({
    required this.id,
    required this.severity,
    required this.category,
    required this.title,
    required this.message,
    required this.timestamp,
    this.component,
    this.currentValue,
    this.threshold,
    this.escalationTier,
    this.correlationId,
    this.metadata,
  });

  final String id;
  final AlertSeverity severity;
  final AlertCategory category;
  final String title;
  final String message;
  final DateTime timestamp;
  final String? component;
  final double? currentValue;
  final double? threshold;
  final int? escalationTier;
  final String? correlationId;
  final Map<String, dynamic>? metadata;

  Map<String, dynamic> toJson() => {
    'id': id,
    'severity': severity.label,
    'category': category.label,
    'title': title,
    'message': message,
    'timestamp': timestamp.toUtc().toIso8601String(),
    if (component != null) 'component': component,
    if (currentValue != null) 'current_value': currentValue,
    if (threshold != null) 'threshold': threshold,
    if (escalationTier != null) 'escalation_tier': escalationTier,
    if (correlationId != null) 'correlation_id': correlationId,
    if (metadata != null) 'metadata': metadata,
  };

  @override
  String toString() => 'Alert(${severity.label}: ${category.label} - $title)';
}

// ═══════════════════════════════════════════════════════════════════════════
// ESCALATION TIER
// ═══════════════════════════════════════════════════════════════════════════

/// Escalation tiers for critical alerts.
class EscalationTier {
  EscalationTier({
    required this.tierNumber,
    required this.name,
    required this.delayMinutes,
    this.notificationChannels = const [],
  });

  final int tierNumber;
  final String name;
  final int delayMinutes;
  final List<String> notificationChannels;
}

// ═══════════════════════════════════════════════════════════════════════════
// ALERT THRESHOLD CONFIGURATION
// ═══════════════════════════════════════════════════════════════════════════

/// Configurable thresholds for alert generation.
class AlertThresholds {
  const AlertThresholds({
    this.crashSpikeRate = 10,       // crashes per minute
    this.authFailureThreshold = 5,  // consecutive auth failures
    this.apiLatencyThresholdMs = 2000, // slow API threshold
    this.databaseTimeoutMs = 5000,  // database timeout threshold
    this.aiFailureThreshold = 3,    // consecutive AI failures
    this.storageFailureThreshold = 3, // consecutive storage failures
    this.queueGrowthThreshold = 100, // sync queue items
    this.syncFailureThreshold = 5,  // consecutive sync failures
    this.rateLimitThreshold = 5,    // rate limit hits per minute
  });

  final int crashSpikeRate;
  final int authFailureThreshold;
  final double apiLatencyThresholdMs;
  final double databaseTimeoutMs;
  final int aiFailureThreshold;
  final int storageFailureThreshold;
  final int queueGrowthThreshold;
  final int syncFailureThreshold;
  final int rateLimitThreshold;
}

// ═══════════════════════════════════════════════════════════════════════════
// ALERT ENGINE
// ═══════════════════════════════════════════════════════════════════════════

/// Enterprise alert engine that evaluates system conditions and generates
/// alerts when thresholds are exceeded. Supports escalation for critical
/// alerts.
class AlertEngine {
  AlertEngine({AlertThresholds? thresholds})
      : _thresholds = thresholds ?? const AlertThresholds();

  final AlertThresholds _thresholds;
  final Queue<Alert> _activeAlerts = Queue();
  final Map<AlertCategory, int> _consecutiveCounts = {};
  static const int _maxActiveAlerts = 100;

  /// Escalation tier definitions for critical alerts.
  final List<EscalationTier> escalationTiers = [
    EscalationTier(
      tierNumber: 1,
      name: 'Team Lead',
      delayMinutes: 5,
      notificationChannels: ['in_app', 'email'],
    ),
    EscalationTier(
      tierNumber: 2,
      name: 'Engineering Manager',
      delayMinutes: 15,
      notificationChannels: ['in_app', 'email', 'sms'],
    ),
    EscalationTier(
      tierNumber: 3,
      name: 'VP Engineering',
      delayMinutes: 30,
      notificationChannels: ['email', 'sms', 'phone'],
    ),
  ];

  // ─── Alert Evaluation ────────────────────────────────────────────────

  /// Evaluate crash data for crash spike alerts.
  void evaluateCrashData(int recentCrashCount, Duration window) {
    final ratePerMinute = recentCrashCount / (window.inMinutes > 0 ? window.inMinutes : 1);
    if (ratePerMinute >= _thresholds.crashSpikeRate) {
      _generateAlert(
        severity: ratePerMinute >= _thresholds.crashSpikeRate * 2
            ? AlertSeverity.emergency
            : AlertSeverity.critical,
        category: AlertCategory.crashSpike,
        title: 'Crash spike detected',
        message: 'Crash rate of ${ratePerMinute.toStringAsFixed(1)}/min exceeds threshold of ${_thresholds.crashSpikeRate}/min',
        currentValue: ratePerMinute,
        threshold: _thresholds.crashSpikeRate.toDouble(),
      );
    }
  }

  /// Evaluate authentication failures.
  void evaluateAuthFailures(int consecutiveAuthFailures) {
    if (consecutiveAuthFailures >= _thresholds.authFailureThreshold) {
      _generateAlert(
        severity: consecutiveAuthFailures >= _thresholds.authFailureThreshold * 2
            ? AlertSeverity.critical
            : AlertSeverity.warning,
        category: AlertCategory.authFailure,
        title: 'Authentication failures detected',
        message: '$consecutiveAuthFailures consecutive auth failures (threshold: ${_thresholds.authFailureThreshold})',
        currentValue: consecutiveAuthFailures.toDouble(),
        threshold: _thresholds.authFailureThreshold.toDouble(),
        component: 'supabase_auth',
      );
    }
  }

  /// Evaluate API latency.
  void evaluateApiLatency(String endpoint, double latencyMs) {
    if (latencyMs >= _thresholds.apiLatencyThresholdMs) {
      _generateAlert(
        severity: latencyMs >= _thresholds.apiLatencyThresholdMs * 2
            ? AlertSeverity.critical
            : AlertSeverity.warning,
        category: AlertCategory.slowApi,
        title: 'Slow API response: $endpoint',
        message: 'API $endpoint responded in ${latencyMs.round()}ms (threshold: ${_thresholds.apiLatencyThresholdMs.round()}ms)',
        currentValue: latencyMs,
        threshold: _thresholds.apiLatencyThresholdMs,
        component: endpoint,
      );
    }
  }

  /// Evaluate database timeout.
  void evaluateDatabaseTimeout(double latencyMs) {
    if (latencyMs >= _thresholds.databaseTimeoutMs) {
      _generateAlert(
        severity: AlertSeverity.critical,
        category: AlertCategory.databaseTimeout,
        title: 'Database timeout detected',
        message: 'Database query took ${latencyMs.round()}ms (threshold: ${_thresholds.databaseTimeoutMs.round()}ms)',
        currentValue: latencyMs,
        threshold: _thresholds.databaseTimeoutMs,
        component: 'supabase_database',
      );
    }
  }

  /// Evaluate AI failures.
  void evaluateAiFailure(int consecutiveAiFailures) {
    _consecutiveCounts[AlertCategory.aiFailure] = consecutiveAiFailures;
    if (consecutiveAiFailures >= _thresholds.aiFailureThreshold) {
      _generateAlert(
        severity: AlertSeverity.critical,
        category: AlertCategory.aiFailure,
        title: 'AI service failures detected',
        message: '$consecutiveAiFailures consecutive AI failures (threshold: ${_thresholds.aiFailureThreshold})',
        currentValue: consecutiveAiFailures.toDouble(),
        threshold: _thresholds.aiFailureThreshold.toDouble(),
        component: 'ai_provider',
      );
    }
  }

  /// Evaluate storage failure.
  void evaluateStorageFailure(int consecutiveStorageFailures) {
    if (consecutiveStorageFailures >= _thresholds.storageFailureThreshold) {
      _generateAlert(
        severity: AlertSeverity.warning,
        category: AlertCategory.storageFailure,
        title: 'Storage failures detected',
        message: '$consecutiveStorageFailures consecutive storage failures',
        currentValue: consecutiveStorageFailures.toDouble(),
        threshold: _thresholds.storageFailureThreshold.toDouble(),
        component: 'supabase_storage',
      );
    }
  }

  /// Evaluate realtime disconnect.
  void evaluateRealtimeDisconnect(bool isConnected) {
    if (!isConnected) {
      _generateAlert(
        severity: AlertSeverity.warning,
        category: AlertCategory.realtimeDisconnect,
        title: 'Realtime connection lost',
        message: 'Supabase realtime channel disconnected',
        component: 'supabase_realtime',
      );
    }
  }

  /// Evaluate queue growth.
  void evaluateQueueGrowth(int queueSize) {
    if (queueSize >= _thresholds.queueGrowthThreshold) {
      _generateAlert(
        severity: queueSize >= _thresholds.queueGrowthThreshold * 5
            ? AlertSeverity.critical
            : AlertSeverity.warning,
        category: AlertCategory.queueGrowth,
        title: 'Sync queue growing',
        message: 'Queue has $queueSize pending items (threshold: ${_thresholds.queueGrowthThreshold})',
        currentValue: queueSize.toDouble(),
        threshold: _thresholds.queueGrowthThreshold.toDouble(),
        component: 'sync_queue',
      );
    }
  }

  /// Evaluate sync failure.
  void evaluateSyncFailure(int consecutiveSyncFailures) {
    if (consecutiveSyncFailures >= _thresholds.syncFailureThreshold) {
      _generateAlert(
        severity: AlertSeverity.warning,
        category: AlertCategory.syncFailure,
        title: 'Sync failures detected',
        message: '$consecutiveSyncFailures consecutive sync failures',
        currentValue: consecutiveSyncFailures.toDouble(),
        threshold: _thresholds.syncFailureThreshold.toDouble(),
        component: 'sync_queue',
      );
    }
  }

  /// Evaluate rate limit spikes.
  void evaluateRateLimit(int rateLimitHits) {
    if (rateLimitHits >= _thresholds.rateLimitThreshold) {
      _generateAlert(
        severity: AlertSeverity.warning,
        category: AlertCategory.rateLimitSpike,
        title: 'Rate limit spike detected',
        message: '$rateLimitHits rate limit responses in current window',
        currentValue: rateLimitHits.toDouble(),
        threshold: _thresholds.rateLimitThreshold.toDouble(),
      );
    }
  }

  // ─── Alert Generation ────────────────────────────────────────────────

  void _generateAlert({
    required AlertSeverity severity,
    required AlertCategory category,
    required String title,
    required String message,
    String? component,
    double? currentValue,
    double? threshold,
    Map<String, dynamic>? metadata,
  }) {
    final alert = Alert(
      id: 'alert-${DateTime.now().millisecondsSinceEpoch}',
      severity: severity,
      category: category,
      title: title,
      message: message,
      timestamp: DateTime.now(),
      component: component,
      currentValue: currentValue,
      threshold: threshold,
      escalationTier: severity.priority >= AlertSeverity.critical.priority ? 1 : null,
      correlationId: StructuredLogger.correlationId,
      metadata: metadata,
    );

    _activeAlerts.add(alert);
    if (_activeAlerts.length > _maxActiveAlerts) {
      _activeAlerts.removeFirst();
    }

    // Log the alert
    if (severity.priority >= AlertSeverity.critical.priority) {
      StructuredLogger.critical(
        'ALERT: $title',
        errorCode: 'ALERT_${category.label.toUpperCase()}',
        metadata: alert.toJson(),
      );
    } else {
      StructuredLogger.warning(
        'ALERT: $title',
        metadata: alert.toJson(),
      );
    }

    // Initiate escalation for critical/emergency alerts
    if (severity.priority >= AlertSeverity.critical.priority) {
      _initiateEscalation(alert);
    }
  }

  /// Initiate escalation for a critical alert.
  void _initiateEscalation(Alert alert) {
    final tier = escalationTiers.firstWhere(
      (t) => t.tierNumber == (alert.escalationTier ?? 1),
    );
    StructuredLogger.critical(
      'ALERT ESCALATION: Tier ${tier.tierNumber} (${tier.name}) — ${alert.title}',
      metadata: {
        'alert_id': alert.id,
        'tier': tier.tierNumber,
        'channels': tier.notificationChannels,
        'delay_minutes': tier.delayMinutes,
      },
    );
  }

  // ─── Alert Access ────────────────────────────────────────────────────

  /// Get all active alerts.
  List<Alert> get activeAlerts => List.unmodifiable(_activeAlerts);

  /// Get alerts filtered by severity.
  List<Alert> getAlertsBySeverity(AlertSeverity severity) =>
      _activeAlerts.where((a) => a.severity == severity).toList();

  /// Get alerts filtered by category.
  List<Alert> getAlertsByCategory(AlertCategory category) =>
      _activeAlerts.where((a) => a.category == category).toList();

  /// Number of active alerts.
  int get activeAlertCount => _activeAlerts.length;

  /// Number of critical/emergency alerts.
  int get criticalAlertCount =>
      _activeAlerts.where((a) => a.severity.priority >= AlertSeverity.critical.priority).length;

  /// Clear alerts that have been resolved.
  void clearResolvedAlerts() {
    // In production, this would remove alerts that have been acknowledged
    // and the underlying condition has been resolved
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// RIVERPOD PROVIDERS
// ═══════════════════════════════════════════════════════════════════════════

/// Provider for alert thresholds configuration.
final alertThresholdsProvider = Provider<AlertThresholds>((ref) {
  return const AlertThresholds();
});

/// Provider for alert engine instance.
final alertEngineProvider = Provider<AlertEngine>((ref) {
  final thresholds = ref.watch(alertThresholdsProvider);
  return AlertEngine(thresholds: thresholds);
});

/// Provider for active alerts list.
final activeAlertsProvider = Provider<List<Alert>>((ref) {
  final engine = ref.watch(alertEngineProvider);
  return engine.activeAlerts;
});

/// Provider for critical alert count.
final criticalAlertCountProvider = Provider<int>((ref) {
  final engine = ref.watch(alertEngineProvider);
  return engine.criticalAlertCount;
});
